"""eliminar uuid4

Revision ID: 6b264f412bf3
Revises: ce366017772f
Create Date: 2025-11-05 08:15:23.829321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b264f412bf3'
down_revision = 'ce366017772f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categorias', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categorias', type_='unique')
    # ### end Alembic commands ###
